# Generated by Django 4.0.3 on 2022-05-21 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name = 'Usuario',
            fields = [
                ('dni', models.CharField(
                    editable = False, 
                    max_length=8, 
                    primary_key=True, 
                    serialize=False)),
                ('nombre_apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(
                    choices = [('F', 'Femenino'), ('M', 'Masculino')], 
                    max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('es_adm', models.BooleanField(default=False)),
                ('fecha_nacimiento', models.DateField()),
                ('contrasenia', models.CharField(max_length=30)),
                ('clave_alfanumerica', models.CharField(max_length=5)), 
            ],
        ),
        migrations.CreateModel(
            name = 'Vacuna',
            fields = [
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name = 'Vacunatorio',
            fields = [
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name = 'VacunaVacunatorio',
            fields = [
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('stock_actual', models.PositiveIntegerField()),
                ('vacuna', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    to='gestion_de_usuarios.vacuna')),
                ('vacunatorio', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    to='gestion_de_usuarios.vacunatorio')),
            ],
        ),
        migrations.CreateModel(
            name = 'Vacunador',
            fields = [
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, 
                    to='gestion_de_usuarios.usuario', 
                    unique=True)),
                ('vacunatorio_de_trabajo', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    to='gestion_de_usuarios.vacunatorio')),
            ],
        ),
        migrations.CreateModel(
            name = 'VacunaAplicada',
            fields = [
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('fecha', models.DateField(
                    default=datetime.date.today)),
                ('marca', models.CharField(
                    blank=True, 
                    max_length=20, 
                    null=True)),
                ('lote', models.CharField(
                    blank=True, 
                    max_length=20, 
                    null=True)),
                ('con_nosotros', models.BooleanField()),
                ('usuario', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, 
                    to='gestion_de_usuarios.usuario')),
                ('vacuna', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING, 
                    to='gestion_de_usuarios.vacuna')),
            ],
        ),
        migrations.AddField(
            model_name = 'usuario',
            name = 'vacunatorio_pref',
            field = models.ForeignKey(
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                to='gestion_de_usuarios.vacunatorio'),
        ),
        migrations.CreateModel(
            name = 'Inscripcion',
            fields = [
                ('id', models.BigAutoField(
                    auto_created=True, 
                    primary_key=True, 
                    serialize=False, 
                    verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(
                    null=True, 
                    on_delete=django.db.models.deletion.SET_NULL, 
                    to='gestion_de_usuarios.usuario')),
                ('vacuna', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    to='gestion_de_usuarios.vacuna')),
                ('vacunatorio', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, 
                    to='gestion_de_usuarios.vacunatorio')),
            ],
        ),
    ]
