# Generated by Django 4.0.3 on 2022-05-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'usuario',
            name = 'de_riesgo',
            field = models.BooleanField(default = False),
        ),
    ]
