# Generated by Django 4.0.5 on 2022-07-04 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_usuarios', '0006_alter_vacunaaplicada_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'usuario',
            name = 'rol_actual',
            field = models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name = 'vacuna',
            name = 'inscriptos',
            field = models.ManyToManyField(blank=True, default=None, related_name='campañas_inscriptas', through='gestion_de_usuarios.Inscripcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name = 'vacuna',
            name = 'tienen_aplicaciones',
            field = models.ManyToManyField(blank=True, default=None, related_name='vacunas_aplicadas', through='gestion_de_usuarios.VacunaAplicada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name = 'vacunatorio',
            name = 'vacunas_en_stock',
            field = models.ManyToManyField(blank=True, default=None, related_name='vacunatorios_con_stock', through='gestion_de_usuarios.VacunaVacunatorio', to='gestion_de_usuarios.vacuna'),
        ),
    ]
