# Generated by Django 4.0.5 on 2022-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_usuarios', '0008_alter_usuario_rol_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'usuario',
            name = 'rol_actual',
            field = models.CharField(choices=[('Vac', 'Vacunador'), ('Adm', 'Administrador'), ('User', 'Usuario comun')], default=None, max_length=4, null=True),
        ),
    ]
