# Generated by Django 4.0.4 on 2022-07-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_usuarios', '0012_alter_usuario_rol_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name = 'usuario',
            name = 'rol_actual',
            field = models.CharField(blank = True, default = None,
                                      max_length = 20, null = True),
        ),
    ]
