# Generated by Django 4.0.3 on 2022-07-05 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_usuarios', '0013_alter_usuario_rol_actual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacunavacunatorio',
            old_name='stock_actual',
            new_name='stock_remanente',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vacunaaplicada',
            name='vacunatorio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_de_usuarios.vacunatorio'),
        ),
        migrations.AlterUniqueTogether(
            name='vacunaaplicada',
            unique_together={('usuario', 'vacuna')},
        ),
        migrations.CreateModel(
            name='VacunasNoAplicadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_de_usuarios.vacuna')),
                ('vacunatorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_de_usuarios.vacunatorio')),
            ],
            options={
                'verbose_name_plural': 'Vacunas_pospuestas',
            },
        ),
    ]
